### ISSUE TITLE
EX inputs with different combinations

### ISSUE THREAD

**Issue by gdelahodde** [Neph0/fightingGameInputs-tti#1]
Hey, great project!

I was wondering if your todo-list included EX inputs with different combinations, such as Ibuki's EX kunai throws in SFV. Since the range depends on the input, it would be cool to handle that too :3

Thanks a lot!

**Comment by Neph0** [comment]
Hello! Thanks.

I could do that very easily, just have to tweak the icons and add some lines to the code. I'll do that in the afternoon :smile:

**Comment by Neph0** [comment]
Added lpmp, lphp, mphp, lkmk, lkhk, mkhk. Issue closed.
